import { BASE, browser } from "./lib.mjs";
const b = await browser();
const p = await b.newPage({ viewport: { width: 1400, height: 1200 } });
await p.goto(`${BASE}/ar/used-cars`, { waitUntil: "domcontentloaded" });
await p.waitForSelector(".asq-toolbar");
await p.waitForTimeout(800);
console.log("sliders (closed panel):", await p.$$eval("[role=slider]", (e) => e.map((x) => x.getAttribute("aria-label"))));
await p.locator("button.icon-filter").click();
await p.waitForTimeout(500);
console.log("sliders (open panel):", await p.$$eval("[role=slider]", (e) => e.map((x) => x.getAttribute("aria-label"))));
console.log("cards:", await p.$$eval("article.asq-card", (cs) => cs.map((c) => [c.querySelector(".asq-card__title a").getAttribute("href"), c.querySelector(".asq-card__price").textContent])));
await b.close();
